sudo: false
dist: trusty

language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env: WP_VERSION=latest
    - php: 7.2
      env: WP_VERSION=latest
    - php: 7.1
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=latest
    - php: 5.4
      env: WP_VERSION=4.7.12

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - composer install
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      composer global require "phpunit/phpunit=4.8.*|5.7.*"
    fi
  - |
    composer global require phpmd/phpmd
    composer global require wp-coding-standards/wpcs
    phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs
    composer install --no-interaction
  - |
    if [[ "$WP_TRAVISCI" == "travis:jshint" ]] ; then
      npm install
      node --version
      npm --version
      grunt --version
    fi

script:
  - |
    if [[ "$WP_TRAVISCI" == "travis:phpvalidate" ]] ; then
      grunt checktextdomain
      phpmd classes text codesize,naming,unusedcode
      phpcs --standard=phpcs.ruleset.xml $(find . -name '*.php')
    fi
  - |
    if [[ "$WP_TRAVISCI" == "travis:codecoverage" ]] ; then
      phpunit --coverage-clover build/logs/clover.xml
    else
      phpunit
      WP_MULTISITE=1 phpunit
    fi
  - |
   if [[ "$WP_TRAVISCI" == "travis:jshint" ]] ; then
     grunt jshint
   fi


cache:
  apt: true
  bundler: true
  directories:
  - vendor
  - $HOME/.composer/cache
  - node_modules

after_script:
  # Push coverage off to Codecov
- |
  if [[ "$WP_TRAVISCI" == "travis:codecoverage" ]] ; then
    bash <(curl -s https://codecov.io/bash)
  fi

notifications:
  slack:
    rooms:
      secure: lCaCsjKe//fJpcqC42Av8EtlxoFchul+s0iEqQX9DMjq62BS4HJ9jmJvXiGn/4VFhyZg+Guvoqn8G7PZsdXYLugt48itV8M9bii1mg/SWz1KlMs039nJ4wzwPWMqM2BeguZarWb5UM8os9yDWRflGcq/0d7v6CNjA9Fj8oclChQoCmiWGN9zC3q08Aag/9dWsAgCiuzS7dRLsmYl/T43EZjFiNHAVztm6mtRvkRZzicq7OKy6/BJplK8wma20bIy2VZPd665dkuaJjYV+LtRJyaK1/wyEHbKVjPnG4E6w/LvWoDZwoBuGtSf/KR5C2REhI6Ot4E7/1N6QavPNLhaHSJhH+3U37P9s5klyeV9tPXE5wyzn92Be8ahpQC1MJY1Z/XutGh5da3oEbye6Pkupplx0Zur0acdcbup8MbUUDe1UBe6h7ms36Deap4OW9XHkT/+L8NvBzYuReco0phgzQiLnTJujzhg6u68v188XKyfZd08jHvUL8pPaDex95FXTemR+3y9VZtqiQOpVsoJisBPbzLgEIPuR/elcNRMx0glWLHRv0tcsArrrHdp2f3SU7ApPoGXgRhvVPj74mP9HvGJK61p0qnL1dv4/vWkpJuAzw+J+19sgZLgnZobfJyzjzm+wjvhD2PwMO8iqqKtm4mNV6w+479exazBlQmBdW0=
    on_start: never
    on_failure: always
    on_success: change
