name: Plugin asset/readme update

on:
  push:
    branches:
      - master
    paths:
      - 'readme.md'
      - '.wordpress-org/**'

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: WordPress.org plugin asset/readme update
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          README_NAME: 'readme.md'
          IGNORE_OTHER_FILES: 'true'
          SVN_USERNAME: ${{ secrets.WORDPRESS_ORG_SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.WORDPRESS_ORG_SVN_PASSWORD }}
